name: Clang

on:
  push:
    branches:
      - master  # Trigger on push to 'master' branch
  pull_request:
    branches:
      - master  # Trigger on pull request targeting 'master' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu environment for the build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the repository code

    - name: Configure CMake with Clang
      run: cmake -S . -B Build -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++  # Configure CMake with Clang as the compiler

    - name: Build
      run: cmake --build Build  # Build the project using CMake

    - name: Run StateMachineApp
      run: ./Build/StateMachineApp  # Run the built executable
